spring:
  mail:
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true
    efault-encoding: UTF-8  #设置编码 防止乱码
    protocol: smtp
    host: smtp.mxhichina.com
    port: 25
    username: duliu@devnp.com
    password: #账号密码
  messages:
    encoding: UTF-8
    basename: com/devnp/message/MailMessage
  
